spring.application.name=ShamimZariWalaBackend
spring.docker.compose.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=lovethepoor
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=DEBUG
